name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  REACT_APP_MAPBOX_TOKEN: ${{ secrets.REACT_APP_MAPBOX_TOKEN }}
  REACT_APP_MAPBOX_STYLE_URL: "${{ secrets.REACT_APP_MAPBOX_STYLE_URL }}"
  REACT_APP_MAPBOX_USER_STYLE_ID: "${{ secrets.REACT_APP_MAPBOX_USER_STYLE_ID }}"
  REACT_APP_NAME: "Atlas Viewer"
  REACT_APP_VERSION: "1.0.0"
  REACT_APP_THEME: "dark"
  REACT_APP_LOGO_PATH: "%PUBLIC_URL%/assets/integral-analytics-logo.png"
  REACT_APP_DEBUG: "false"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack
        run: corepack enable

      - name: Use project Yarn version
        run: corepack prepare yarn@4.4.0 --activate

      - name: Install dependencies
        run: yarn install

      - name: Copy parquet_wasm_bg.wasm to public
        run: cp node_modules/parquet-wasm/esm/parquet_wasm_bg.wasm public/

      - name: Build
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
